backend/src/config/api-config.ts
backend/src/controllers/checklist.controller.ts
backend/src/controllers/employee.controller.ts
backend/src/data-contracts/checklist/data-contracts.ts
backend/src/data-contracts/employee/data-contracts.ts
backend/src/data-contracts/simulatorserver/data-contracts.ts
backend/src/responses/checklist.response.ts
backend/src/responses/employee.response.ts
backend/src/server.ts
backend/src/services/api.service.ts
frontend/package.json
frontend/src/components/activity-list-item/activity-list-item.component.tsx
frontend/src/components/add-activity-modal/add-activity-modal.component.tsx
frontend/src/components/assign-mentor-modal/assign-mentor-modal.component.tsx
frontend/src/components/checklist-header/checklist-header.component.tsx
frontend/src/components/delegate-checklist-modal/delegate-checklist-modal.component.tsx
frontend/src/components/delegate-checklist-modal/delegate-multiple-checklists-modal.component.tsx
frontend/src/components/ongoing-checklists-table/ongoing-checklists-table.component.tsx
frontend/src/components/stepper/stepper.component.tsx
frontend/src/contexts/app.context.tsx
frontend/src/data-contracts/backend/data-contracts.ts
frontend/src/layouts/default-layout/default-layout.component.tsx
frontend/src/pages/admin/index.tsx
frontend/src/pages/index.tsx
frontend/src/pages/start/[userId]/index.tsx
frontend/src/pages/start/index.tsx
frontend/src/services/checklist-service/checklist-service.ts
frontend/src/swagger-typescript-api.ts
frontend/yarn.lock

feature: new features and improvements

---

backend/package.json
backend/src/controllers/checklist.controller.ts
backend/src/controllers/employee.controller.ts
backend/src/services/api.service.ts
backend/yarn.lock
frontend/package.json

Lägg till request.user i backend så att api-service vet vilken användare som anropar, och så att man kan använda user-objektet i controllers osv.

Add user to request object

---

backend/src/controllers/health.controller.ts
backend/src/controllers/organization.controller.ts

Missing user object

---

backend/src/data-contracts/checklist/data-contracts.ts
frontend/src/components/ongoing-checklists-table/ongoing-checklists-table.component.tsx
frontend/src/components/stepper/stepper.component.tsx
frontend/src/data-contracts/backend/data-contracts.ts
frontend/src/pages/start/[userId]/index.tsx
frontend/src/pages/start/index.tsx
frontend/src/utils/fulfilment-status-utils.ts
frontend/src/utils/get-checklist-status.tsx

feature: overview table update

---

frontend/src/components/stepper/stepper.component.tsx
frontend/src/pages/start/[userId]/index.tsx
frontend/src/services/checklist-service/checklist-service.ts

Refactoring and null checks

---

frontend/src/layouts/default-layout/default-layout.component.tsx
frontend/src/pages/[userId]/index.tsx

fix: fixed refresh error

---

backend/src/services/api.service.ts
frontend/public/locales/sv/delegation.json
frontend/src/components/delegate-checklists-modal/delegate-checklists-modal.component.tsx
frontend/src/pages/[userId]/index.tsx

feature: handling of delegation conflicts

---

backend/src/app.ts
backend/src/interfaces/users.interface.ts
backend/src/responses/user.response.ts
backend/src/services/authorization.service.ts
frontend/src/data-contracts/backend/data-contracts.ts
frontend/src/interfaces/permissions.ts
frontend/src/pages/[userId]/index.tsx
frontend/src/services/user-service/defaults.ts

isManager as permission

---

frontend/src/components/activity-list-item/activity-list-item.component.tsx
frontend/src/components/add-activity-modal/add-activity-modal.component.tsx
frontend/src/components/assign-mentor-modal/assign-mentor-modal.component.tsx
frontend/src/components/checklist-sidebar/checklist-sidebar.component.tsx
frontend/src/components/delegate-checklists-modal/delegate-checklists-modal.component.tsx
frontend/src/components/ongoing-checklists-table/ongoing-checklists-table.component.tsx
frontend/src/contexts/app.context.tsx
frontend/src/layouts/default-layout/default-layout.component.tsx
frontend/src/pages/[userId]/index.tsx
frontend/src/pages/index.tsx
frontend/src/services/checklist-service/use-checklist-store.ts
frontend/src/services/checklist-service/use-checklist.ts
frontend/src/utils/count-tasks.ts

feat: use checklist hook

---

frontend/src/services/checklist-service/use-checklist.ts

Always set data on page load

---

frontend/public/locales/sv/common.json
frontend/src/layouts/page-header/page-header.component.tsx

feature: added admin navigation

---

frontend/src/components/add-activity-modal/add-activity-modal.component.tsx
frontend/src/components/edit-task-modal/edit-task-modal.component.tsx

Focus heading input on modal open

---

frontend/src/pages/[userId]/index.tsx

Show phase description

---

frontend/public/locales/sv/task.json
frontend/src/components/activity-list-item/activity-list-item.component.tsx

feature: display task fulfilment username

---

frontend/src/components/activity-list-item/activity-list-item.component.tsx
frontend/src/pages/[userId]/index.tsx

fix: custom task edit restriction

---

frontend/public/locales/sv/delegation.json
frontend/src/components/checklist-sidebar/checklist-sidebar.component.tsx
frontend/src/pages/[userId]/index.tsx

fix: delegation restriction

---

frontend/src/components/add-activity-modal/add-activity-modal.component.tsx
frontend/src/components/edit-task-modal/edit-task-modal.component.tsx
frontend/src/services/checklist-service/checklist-service.ts

fix: custom activity sorting

---

frontend/src/layouts/default-layout/default-layout.component.tsx
frontend/src/layouts/main/main.component.tsx
frontend/src/pages/index.tsx
frontend/src/styles/components.scss

uf-11346 fix: layout width

---

backend/src/controllers/checklist.controller.ts
backend/src/data-contracts/checklist/data-contracts.ts
backend/src/responses/checklist.response.ts
frontend/cypress/e2e/admin/ongoing-introductions.cy.ts
frontend/cypress/fixtures/admin-ongoing-introductions.ts
frontend/public/locales/sv/common.json
frontend/src/components/admin/admin-ongoing-introductions-table/admin-ongoing-introductions-table.component.tsx
frontend/src/data-contracts/backend/data-contracts.ts
frontend/src/pages/admin/checklists.tsx
frontend/src/services/checklist-service/checklist-service.ts
frontend/src/services/checklist-service/use-checklist-store.ts
frontend/src/services/checklist-service/use-ongoing-checklists.ts

uf-7624 feature: admin ongoing introductions

---

frontend/src/layouts/main/main.component.tsx
frontend/src/pages/admin/templates/[orgid]/[templateid].tsx
frontend/src/services/featureflag-service.ts

Disable versioning of templates in the GUI:
* Do not allow creating new versions of templates.
* Allow creation and deletion of tasks in active templates.

Disable template versioning

---

backend/src/controllers/organization.controller.ts
frontend/src/components/admin/admin-template-sidebar/admin-template-sidebar.component.tsx
frontend/src/layouts/main/main.component.tsx
frontend/src/pages/admin/templates/[orgid]/[templateid].tsx
frontend/src/services/organization-service.ts

uf-11739 fix: filtering template sidebar activities by role type

---

frontend/public/locales/sv/user.json
frontend/src/components/activity-list-item/activity-list-item.component.tsx
frontend/src/pages/[userId]/index.tsx
frontend/src/services/user-service/use-user-information-store.ts
frontend/src/services/user-service/use-user-information.ts

uf 11540 feature: implemented store to hold user information

---

frontend/src/components/ongoing-checklists-table/ongoing-checklists-table.component.tsx

uf-11819 fix: checked introductions

---

frontend/src/pages/admin/templates/[orgid]/index.tsx

fix: changed color of create template confirmation

---

frontend/src/pages/admin/templates/[orgid]/[templateid].tsx

uf-14174 fix: order of created activities

---

frontend/src/pages/admin/templates/[orgid]/[templateid].tsx

uf-14188 fix: template background color

---

frontend/src/components/activity-list-item/activity-list-item.component.tsx
frontend/src/components/admin/admin-ongoing-introductions-table/admin-ongoing-introductions-table.component.tsx
frontend/src/components/common/introduction-activity-list/introduction-activity-list.component.tsx
frontend/src/components/common/introduction-fulfill-all-tasks-checkbox/introduction-fulfill-all-tasks-checkbox.component.tsx
frontend/src/components/common/introduction-phase-menu/introduction-phase-menu.component.tsx
frontend/src/components/common/introduction-view-toggle/introduction-view-toggle.component.tsx
frontend/src/pages/admin/[userId]/index.tsx
frontend/src/services/checklist-service/use-managed-checklists.ts

uf-7625 feature: display manager introduction in admin ui

---

backend/src/app.ts
backend/src/controllers/template.controller.ts

Error handling for users not in employee (test users etc)

---

frontend/public/locales/sv/task.json
frontend/src/components/admin/admin-edit-task-modal/admin-edit-task-modal.component.tsx

uf-14258 fix: adjustment of edit and create activity modal

---

backend/src/services/api.service.ts

uf-14335 feature: change of header

---

frontend/src/components/assign-mentor-modal/assign-mentor-modal.component.tsx
frontend/src/services/user-service/user-service.ts

uf-14346 fix: mentor avatar initials

---

backend/src/controllers/employee.controller.ts
frontend/public/locales/sv/common.json
frontend/src/components/assign-mentor-modal/assign-mentor-modal.component.tsx
frontend/src/components/delegate-checklists-modal/delegate-checklists-modal.component.tsx
frontend/src/components/search-employee/search-employee.component.tsx
frontend/src/services/checklist-service/checklist-service.ts

uf-14360 feature: search employee by email

---

frontend/public/locales/sv/task.json
frontend/src/components/add-activity-modal/add-activity-modal.component.tsx
frontend/src/components/admin/admin-edit-task-modal/admin-edit-task-modal.component.tsx
frontend/src/components/edit-task-modal/edit-task-modal.component.tsx

Uf 14352/feature info about if text is too long

---

frontend/src/services/user-service/use-user-information.ts

fix: preventing calls without defined username

---

frontend/package.json
frontend/yarn.lock

feature: shared components update

---

backend/src/app.ts
backend/src/services/organization.service.ts
frontend/src/pages/admin/templates/[orgid]/[templateid].tsx

Behörighetsstyrning så att avdelningsadministratörer får administrera från sin nivå 2 och nedåt i Sundsvalls kommuns organisationsträd, men från nivå 1 (toppnivå) i de kommunala bolagen.
Med andra ord så är avdelningsadministratörer i de kommunala bolagen en "superadmin" för just det bolaget, medan de inom kommunen är förvaltningsadministratörer.

Level 2 permissions (level 1 for companies)

---

backend/src/app.ts

Null check when logging

---

frontend/src/components/admin/admin-ongoing-introductions-table/admin-ongoing-introductions-table.component.tsx
frontend/src/services/checklist-service/use-ongoing-checklists.ts

uf-14459 fix: ongoing introductions for department admin

---

frontend/cypress/e2e/admin/org-templates.cy.ts
frontend/cypress/e2e/admin/template-overview.cy.ts
frontend/cypress/fixtures/templates-org-2669.json
frontend/public/locales/sv/templates.json
frontend/src/pages/admin/templates/[orgid]/[templateid].tsx
frontend/src/pages/admin/templates/[orgid]/index.tsx

uf-14456 feature: template design update

---

frontend/cypress/e2e/user/as-manager-introduction.cy.ts
frontend/src/components/task-modal/task-modal.component.tsx

uf-14481 fix: refresh on create and update custom task

---

frontend/src/services/template-service/template-service.ts

uf-14494 fix: added organization id to template name and changed display name

---

frontend/src/components/checklist-sidebar/checklist-sidebar.component.tsx
frontend/src/pages/[userId]/index.tsx
frontend/src/pages/admin/[userId]/index.tsx

Om man tittar på en delegerad checklista (dvs man har fått den delegerad till sig) så ska man inte kunna ta bort delegerade användare (sig själv eller andra).

Do not allow delegated users to remove delegated users

---

backend/src/data-contracts/checklist/data-contracts.ts
backend/src/data-contracts/employee/data-contracts.ts
backend/src/responses/checklist.response.ts
frontend/public/locales/sv/task.json
frontend/src/components/task-modal/task-modal.component.tsx
frontend/src/data-contracts/backend/data-contracts.ts
frontend/src/pages/[userId]/index.tsx
frontend/src/services/checklist-service/checklist-service.ts

uf-14458 feature: added role type for custom tasks

---

frontend/src/services/template-service/template-service.ts

fix: changed default communication channel when creating template

---

frontend/src/components/admin/admin-activity-list-item/admin-activity-list-item.component.tsx
frontend/src/pages/admin/templates/[orgid]/[templateid].tsx

feature: adjust button size and add hover state

---

frontend/src/components/activity-list-item/activity-list-item.component.tsx
frontend/src/components/assign-mentor-modal/assign-mentor-modal.component.tsx
frontend/src/components/checklist-sidebar/checklist-sidebar.component.tsx
frontend/src/components/common/introduction-activity-list/introduction-activity-list.component.tsx
frontend/src/components/common/introduction-fulfill-all-tasks-checkbox/introduction-fulfill-all-tasks-checkbox.component.tsx
frontend/src/components/common/introduction-phase-menu/introduction-phase-menu.component.tsx
frontend/src/pages/[userId]/index.tsx
frontend/src/pages/admin/[userId]/index.tsx
frontend/src/services/checklist-service/use-delegated-checklists.ts
frontend/src/services/checklist-service/use-managed-checklists.ts

Handle checklist loading and views

---

frontend/public/locales/sv/delegation.json
frontend/public/locales/sv/mentor.json
frontend/src/components/assign-mentor-modal/assign-mentor-modal.component.tsx

uf-14521 feature: delegate introduction when assigning mentor

---

frontend/src/components/admin/admin-template-sidebar/admin-template-sidebar-activities/admin-template-sidebar-activities.component.tsx
frontend/src/components/admin/admin-template-sidebar/admin-template-sidebar-history/admin-template-sidebar-history.component.tsx
frontend/src/components/admin/admin-template-sidebar/admin-template-sidebar.component.tsx

uf-14544 fix: template sidebar design adjustments

---

frontend/.gitignore
frontend/src/components/common/introduction-phase-menu/introduction-phase-menu.component.tsx
frontend/src/pages/[userId]/index.tsx
frontend/src/pages/admin/[userId]/index.tsx

Fix type error. A small gitignore addition.

---

frontend/public/locales/sv/task.json

uf-14545 fix: remove activity text change

---

backend/src/app.ts
backend/src/controllers/user.controller.ts
backend/src/interfaces/users.interface.ts
backend/src/responses/user.response.ts
frontend/public/locales/sv/delegation.json
frontend/src/components/assign-mentor-modal/assign-mentor-modal.component.tsx
frontend/src/components/checklist-sidebar/checklist-sidebar.component.tsx
frontend/src/data-contracts/backend/data-contracts.ts
frontend/src/pages/[userId]/index.tsx
frontend/src/services/user-service/defaults.ts
frontend/src/services/user-service/user-service.ts

uf-14493 feature: delegated introduction restriction and design adjustments

---

frontend/cypress/e2e/admin/admin-introduction-view.cy.ts
frontend/cypress/e2e/admin/admin-menu.cy.ts
frontend/cypress/e2e/admin/admin-permissions.cy.ts
frontend/cypress/e2e/admin/admin-template-history.cy.ts
frontend/cypress/e2e/admin/org-templates.cy.ts
frontend/cypress/e2e/admin/org-tree.cy.ts
frontend/cypress/e2e/admin/template-overview.cy.ts
frontend/src/components/admin/admin-activity-list-item/admin-activity-list-item.component.tsx
frontend/src/components/admin/admin-edit-task-modal/admin-edit-task-modal.component.tsx
frontend/src/pages/admin/[userId]/index.tsx

fix: admin cypress tests

---

frontend/public/locales/sv/admin.json
frontend/public/locales/sv/common.json
frontend/public/locales/sv/delegation.json
frontend/public/locales/sv/task.json
frontend/src/components/activity-list-item/activity-list-item.component.tsx
frontend/src/components/admin/admin-activity-list-item/admin-activity-list-item.component.tsx
frontend/src/components/admin/admin-edit-task-modal/admin-edit-task-modal.component.tsx
frontend/src/components/assign-mentor-modal/assign-mentor-modal.component.tsx
frontend/src/components/checklist-sidebar/checklist-sidebar.component.tsx
frontend/src/components/ongoing-checklists-table/ongoing-checklists-table.component.tsx
frontend/src/pages/[userId]/index.tsx
frontend/src/pages/admin/[userId]/index.tsx
frontend/src/pages/admin/templates/[orgid]/[templateid].tsx

Develop to main

---

frontend/public/locales/sv/common.json
frontend/public/locales/sv/login.json

Change description etc

---

frontend/public/locales/sv/common.json
frontend/src/components/common/info-banner/info-banner.component.tsx
frontend/src/layouts/default-layout/default-layout.component.tsx

uf-15291 feature: information banner

---

frontend/src/utils/fulfilment-status-utils.ts

Lägg till hantering av tidsperiodsträngen P1M

Handle one month timeToComplete P1M

---

backend/src/app.ts
backend/src/interfaces/profile.interface.ts

Justera utseendet på profilen som förväntas från IDP:n då prod nu går mot Mobilitguard istället för ADFS.

Adjust profile for MG IPD claims
